### ISSUE TITLE
AttributeError: module 'safetensors' has no attribute 'torch'

### ISSUE THREAD

**Issue by gadicc** [huggingface/safetensors#128]
Hey.  Firstly, big thanks for all your amazing work on this!  And for the PRs to diffusers.  This is going to be so awesome for models deployed to a serverless GPU environment and I really can't wait to try it.

Should torch support work in the latest released version (0.2.5)?

I feel like I must be doing something stupid here, and admit that I'm very new to Python, but I'm trying to get this working in diffusers and get this error regardless of whether I install via conda (with python 3.9) or pip (with python 3.10).

Here's from diffusers:

`pipeline.save_pretrained(args.output_dir, safe_serialization=True)`

```
Traceback (most recent call last):
  File "handle_request", line 81, in handle_request
    FutureStatic,
  File "/api/server.py", line 36, in inference
    output = user_src.inference(model_inputs)
  File "/api/app.py", line 281, in inference
    result = TrainDreamBooth(model_id, pipeline, model_inputs, call_inputs)
  File "/api/train_dreambooth.py", line 120, in TrainDreamBooth
    result = main(args, pipeline)
  File "/api/train_dreambooth.py", line 712, in main
    pipeline.save_pretrained(args.output_dir, safe_serialization=True)
  File "/api/diffusers/src/diffusers/pipeline_utils.py", line 248, in save_pretrained
    save_method(
  File "/api/diffusers/src/diffusers/modeling_utils.py", line 224, in save_pretrained
    save_function = safetensors.torch.save_file if safe_serialization else torch.save
AttributeError: module 'safetensors' has no attribute 'torch'
```

and here's from the python interpreter:

```bash
$ python
Python 3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import safetensors

>>> print(safetensors)
<module 'safetensors' from '/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors/__init__.py'>

>>> safetensors.torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'safetensors' has no attribute 'torch'

>>> safetensors.__dict__
{'__name__': 'safetensors', '__doc__': None, '__package__': 'safetensors', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7ff358dccac0>, '__spec__': ModuleSpec(name='safetensors', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7ff358dccac0>, origin='/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors/__init__.py', submodule_search_locations=['/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors']), '__path__': ['/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors'], '__file__': '/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors/__init__.py', '__cached__': '/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors/__pycache__/__init__.cpython-39.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'hasattr': <built-in function hasattr>, 'hash': <built-in function hash>, 'hex': <built-in function hex>, 'id': <built-in function id>, 'input': <built-in function input>, 'isinstance': <built-in function isinstance>, 'issubclass': <built-in function issubclass>, 'iter': <built-in function iter>, 'len': <built-in function len>, 'locals': <built-in function locals>, 'max': <built-in function max>, 'min': <built-in function min>, 'next': <built-in function next>, 'oct': <built-in function oct>, 'ord': <built-in function ord>, 'pow': <built-in function pow>, 'print': <built-in function print>, 'repr': <built-in function repr>, 'round': <built-in function round>, 'setattr': <built-in function setattr>, 'sorted': <built-in function sorted>, 'sum': <built-in function sum>, 'vars': <built-in function vars>, 'None': None, 'Ellipsis': Ellipsis, 'NotImplemented': NotImplemented, 'False': False, 'True': True, 'bool': <class 'bool'>, 'memoryview': <class 'memoryview'>, 'bytearray': <class 'bytearray'>, 'bytes': <class 'bytes'>, 'classmethod': <class 'classmethod'>, 'complex': <class 'complex'>, 'dict': <class 'dict'>, 'enumerate': <class 'enumerate'>, 'filter': <class 'filter'>, 'float': <class 'float'>, 'frozenset': <class 'frozenset'>, 'property': <class 'property'>, 'int': <class 'int'>, 'list': <class 'list'>, 'map': <class 'map'>, 'object': <class 'object'>, 'range': <class 'range'>, 'reversed': <class 'reversed'>, 'set': <class 'set'>, 'slice': <class 'slice'>, 'staticmethod': <class 'staticmethod'>, 'str': <class 'str'>, 'super': <class 'super'>, 'tuple': <class 'tuple'>, 'type': <class 'type'>, 'zip': <class 'zip'>, '__debug__': True, 'BaseException': <class 'BaseException'>, 'Exception': <class 'Exception'>, 'TypeError': <class 'TypeError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'StopIteration': <class 'StopIteration'>, 'GeneratorExit': <class 'GeneratorExit'>, 'SystemExit': <class 'SystemExit'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'ImportError': <class 'ImportError'>, 'ModuleNotFoundError': <class 'ModuleNotFoundError'>, 'OSError': <class 'OSError'>, 'EnvironmentError': <class 'OSError'>, 'IOError': <class 'OSError'>, 'EOFError': <class 'EOFError'>, 'RuntimeError': <class 'RuntimeError'>, 'RecursionError': <class 'RecursionError'>, 'NotImplementedError': <class 'NotImplementedError'>, 'NameError': <class 'NameError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'AttributeError': <class 'AttributeError'>, 'SyntaxError': <class 'SyntaxError'>, 'IndentationError': <class 'IndentationError'>, 'TabError': <class 'TabError'>, 'LookupError': <class 'LookupError'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'ValueError': <class 'ValueError'>, 'UnicodeError': <class 'UnicodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'AssertionError': <class 'AssertionError'>, 'ArithmeticError': <class 'ArithmeticError'>, 'FloatingPointError': <class 'FloatingPointError'>, 'OverflowError': <class 'OverflowError'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'SystemError': <class 'SystemError'>, 'ReferenceError': <class 'ReferenceError'>, 'MemoryError': <class 'MemoryError'>, 'BufferError': <class 'BufferError'>, 'Warning': <class 'Warning'>, 'UserWarning': <class 'UserWarning'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'FutureWarning': <class 'FutureWarning'>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'BytesWarning': <class 'BytesWarning'>, 'ResourceWarning': <class 'ResourceWarning'>, 'ConnectionError': <class 'ConnectionError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'FileExistsError': <class 'FileExistsError'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'InterruptedError': <class 'InterruptedError'>, 'PermissionError': <class 'PermissionError'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'TimeoutError': <class 'TimeoutError'>, 'open': <built-in function open>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'copyright': Copyright (c) 2001-2022 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'license': Type license() to see the full license text, 'help': Type help() for interactive help, or help(object) for help about object., '_': None}, '__version__': '0.2.5', 'safetensors_rust': <module 'safetensors.safetensors_rust' from '/opt/conda/envs/xformers/lib/python3.9/site-packages/safetensors/safetensors_rust.cpython-39-x86_64-linux-gnu.so'>, 'safe_open': <class 'builtins.safe_open'>}
```

**Comment by gadicc** [comment]
Ok I dunno I changed versions of a number of other conda / pip packages and this seems to have fixed itself.  Super excited to play over the weekend.  Thanks again for all your efforts here!

**Comment by DevonPeroutky** [comment]
@gadicc Do you happen to remember any details? I'm getting the same issues with the following environment:

```
import torch
from diffusers import StableDiffusionPipeline

model_id = "stabilityai/stable-diffusion-2"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")
```

Environment:
```
Python Version: 3.9.13
Cuda: 11.2
```

Dependencies 
```
torch==1.13.1
torchaudio==0.12.0+cu116
torchvision==0.14.1
diffusers==0.11.1
sentence-transformers==2.2.2
transformers==4.25.1
```

**Comment by DevonPeroutky** [comment]
Life is funny. I also experience the same fate, where I upgraded a bunch of dependencies and it magically worked. For anyone future visitors. The following fixed it for me:

```
pip install --upgrade diffusers transformers accelerate scipy ftfy safetensors
```

**Comment by Narsil** [comment]
Thanks for sharing. This is relatively confusing though..

**Comment by ryudrigo** [comment]
I just bumped into this error myself. Reinstalling or upgrading packages didn't work. Solved it by adding
`from .torch import save_file, load_file, save, load`
to the `safetensors/__init__.py` file in my conda environment's site_packages folder

it seems to correspond to this path in the repo:  https://github.com/huggingface/safetensors/tree/main/bindings/python/py_src/safetensors/__init__.py

Hope this servers as a workaround and maybe a clue to solve the issue

**Comment by Narsil** [comment]
You don't have any `safetensors.py` file in your path ?

The modification you mention shouldn't ever be necessary, sounds like path issues.

**Comment by ryudrigo** [comment]
indeed I think I don't have this file. I installed via `pip install safetensors` and, when I `import safetensors`, it points to a folder with the following files:
`flax.py  __init__.py  numpy.py  __pycache__  safetensors_rust.cpython-310-x86_64-linux-gnu.so  tensorflow.py  torch.py`

Let me know if I can do anything else to help.

**Comment by Narsil** [comment]
Everything looks normal. 

Do you mind doing 

```python
import safetensors
print(safetensors)
```

And then `ls` within the directory that gets printed ?

**Comment by Narsil** [comment]
Can you try:

```python
from safetensors.torch import load_file, save_file
```
 too ?

**Comment by Narsil** [comment]
I think I see the error now, although I don't understand why python does it that way.

`import safetensors; safetensors.torch` seems to fail because torch is not a member of `safetensors` (which is true), while `from safetensors.torch import load_file` works because it imports correctly from the module. 

I don't remember specifically why Python does this, but seems by design: https://stackoverflow.com/questions/21298833/how-to-only-import-sub-module-without-exec-init-py-in-the-package

Was that the issue ?

Also note, it's not possible to import those submodule within `__init__` because there is no guarantee `torch` will be present within the user's environment (`safetensors` is designed to be agnostic)

**Comment by ryudrigo** [comment]
That was exaclty the issue. I recommend adding this to documentation.

Cheers

**Comment by ShoufaChen** [comment]
Thanks @ryudrigo . Adding `from .torch import save_file, load_file, save, load` solved my problem.

Also kindly note that add this line to the end of the `__init__.py` .

**Comment by nitesr** [comment]
you can do 
`
from safetensors import torch as safetensors_torch

safetensors_torch.save_file(tensors_dict, file_path)
`

**Comment by xiaohei2022** [comment]
I found it was a torch version issue
![image](https://github.com/user-attachments/assets/dc22fd73-1434-4e98-934e-5cf107ae6cd7)
